import os
import sys
import time
import random
from datetime import datetime

import oracledb
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

USER = os.getenv("ORACLE_USER")
PASSWORD = os.getenv("ORACLE_PASSWORD")
HOST = os.getenv("ORACLE_HOST", "oracle.fiap.com.br")
PORT = int(os.getenv("ORACLE_PORT", "1521"))
SERVICE = os.getenv("ORACLE_SERVICE", "ORCL")

if not USER or not PASSWORD:
    sys.exit("[ERRO] ORACLE_USER e ORACLE_PASSWORD precisam estar definidos no .env")

TABELA = "SENSORES_FARMTECH_IOT"

CSV_HISTORICO = "./python/sensores_farmtech_v2.csv" 
INTERVALO_SEGUNDOS = 5  # intervalo entre novas leituras simuladas


def conectar():
    dsn = oracledb.makedsn(HOST, PORT, service_name=SERVICE)
    conn = oracledb.connect(user=USER, password=PASSWORD, dsn=dsn)
    print(f"[OK] Conectado ao Oracle como {USER} ({HOST}:{PORT}/{SERVICE})")
    return conn


def criar_tabela_se_nao_existir(conn):
    cursor = conn.cursor()
    cursor.execute(
        "SELECT COUNT(*) FROM user_tables WHERE table_name = :nome",
        nome=TABELA,
    )
    existe = cursor.fetchone()[0] > 0

    if existe:
        print(f"[OK] Tabela {TABELA} já existe.")
    else:
        cursor.execute(f"""
            CREATE TABLE {TABELA} (
                id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts_leitura  TIMESTAMP NOT NULL,
                umidade     NUMBER(5,2),
                ph          NUMBER(4,2),
                nitrogenio  NUMBER(6,2),
                fosforo     NUMBER(6,2),
                potassio    NUMBER(6,2),
                chuva       NUMBER(1),
                irrigacao   NUMBER(1)
            )
        """)
        conn.commit()
        print(f"[OK] Tabela {TABELA} criada.")
    cursor.close()


def carregar_historico_csv(conn, caminho_csv):
    """Carga inicial (população) a partir do CSV, executada uma única vez."""
    if not os.path.exists(caminho_csv):
        print(f"[AVISO] CSV histórico não encontrado em {caminho_csv}, pulando carga inicial.")
        return

    cursor = conn.cursor()
    cursor.execute(f"SELECT COUNT(*) FROM {TABELA}")
    total_atual = cursor.fetchone()[0]

    if total_atual > 0:
        print(f"[OK] Tabela já possui {total_atual} registros, carga inicial não repetida.")
        cursor.close()
        return

    df = pd.read_csv(caminho_csv)

    dados = [
        (
            str(row["timestamp"]),
            float(row["umidade"]),
            float(row["ph"]),
            float(row["nitrogenio"]),
            float(row["fosforo"]),
            float(row["potassio"]),
            int(row["chuva"]),
            int(row["irrigacao"]),
        )
        for _, row in df.iterrows()
    ]

    cursor.executemany(
        f"""
        INSERT INTO {TABELA}
            (ts_leitura, umidade, ph, nitrogenio, fosforo, potassio, chuva, irrigacao)
        VALUES (TO_TIMESTAMP(:1, 'YYYY-MM-DD HH24:MI:SS'), :2, :3, :4, :5, :6, :7, :8)
        """,
        dados,
    )

    conn.commit()
    print(f"[OK] {len(dados)} registros históricos carregados do CSV.")
    cursor.close()


def gerar_leitura_simulada():
    """Gera uma nova leitura simulada, dentro das faixas documentadas no projeto."""
    return {
        "umidade": round(random.uniform(25, 95), 2),
        "ph": round(random.uniform(5.5, 7.0), 2),
        "nitrogenio": round(random.uniform(10, 140), 2),
        "fosforo": round(random.uniform(5, 145), 2),
        "potassio": round(random.uniform(10, 205), 2),
        "chuva": random.choice([0, 0, 0, 1]),  
        "irrigacao": random.choice([0, 1]),
    }


def inserir_leitura(conn, leitura):
    cursor = conn.cursor()
    cursor.execute(
        f"""
        INSERT INTO {TABELA}
            (ts_leitura, umidade, ph, nitrogenio, fosforo, potassio, chuva, irrigacao)
        VALUES (SYSTIMESTAMP, :umidade, :ph, :nitrogenio, :fosforo, :potassio, :chuva, :irrigacao)
        """,
        leitura,
    )
    conn.commit()
    cursor.close()


def mostrar_ultimas_leituras(conn, n=3):
    cursor = conn.cursor()
    cursor.execute(
        f"""
        SELECT ts_leitura, umidade, ph, nitrogenio, fosforo, potassio, chuva, irrigacao
        FROM {TABELA}
        ORDER BY ts_leitura DESC
        FETCH FIRST :n ROWS ONLY
        """,
        n=n,
    )
    print(f"--- Últimas {n} leituras em {TABELA} ---")
    for linha in cursor.fetchall():
        print(linha)
    cursor.close()


def main():
    conn = conectar()
    criar_tabela_se_nao_existir(conn)
    carregar_historico_csv(conn, CSV_HISTORICO)

    print("\n[INFO] Iniciando ingestão automática de novas leituras...")
    print(f"[INFO] Nova leitura simulada a cada {INTERVALO_SEGUNDOS}s. Pressione CTRL+C para parar.\n")

    try:
        while True:
            leitura = gerar_leitura_simulada()
            inserir_leitura(conn, leitura)
            print(f"[INGESTÃO] {datetime.now().strftime('%H:%M:%S')} -> {leitura}")
            mostrar_ultimas_leituras(conn, n=3)
            print()
            time.sleep(INTERVALO_SEGUNDOS)
    except KeyboardInterrupt:
        print("\n[INFO] Ingestão interrompida pelo usuário.")
    finally:
        conn.close()
        print("[OK] Conexão encerrada.")


if __name__ == "__main__":
    main()
